### ISSUE TITLE
When $HADOOP_HOME is defined beforehand, pydoop.hadoop_exec() fails

### ISSUE THREAD

**Issue by brainstorm** [crs4/pydoop#1]
```
$ python
Python 2.7.3 (default, Aug  1 2012, 05:14:39)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydoop
>>> pydoop.hadoop_exec()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pydoop/__init__.py", line 57, in hadoop_exec
    return _PATH_FINDER.hadoop_exec(hadoop_home)
  File "/usr/local/lib/python2.7/dist-packages/pydoop/hadoop_utils.py", line 235, in hadoop_exec
    PathFinder.__error("hadoop executable", "HADOOP_HOME or PATH")
  File "/usr/local/lib/python2.7/dist-packages/pydoop/hadoop_utils.py", line 209, in __error
    raise ValueError("%s not found, try setting %s" % (what, env_var))
ValueError: hadoop executable not found, try setting HADOOP_HOME or PATH
```

Solved by running `unset HADOOP_HOME`, thanks @ilveroluca and @guillermo-carrasco.

**Comment by elzaggo** [comment]
Not an issue in 1.0
