### ISSUE TITLE
Kerberos Support

### ISSUE THREAD

**Issue by nilesh-unifi** [crs4/pydoop#111]
I am unable to make the module work with a kerberized hadoop. Once I run kinit to initialize a principal, hew of the methods of pydoop.hdfs like 'ls' seems to be working fine. However, methods like 'mkdir', 'read', etc. does not seem to be working. Getting below error. Any insight on this is highly appreciated.

2015-03-25 02:22:40,823 WARN  [main] hdfs.BlockReaderFactory (BlockReaderFactory.java:getRemoteBlockReaderFromTcp(684)) - I/O error constructing remote block reader.
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:529)
	at org.apache.hadoop.hdfs.DFSClient.newConnectedPeer(DFSClient.java:2765)
	at org.apache.hadoop.hdfs.BlockReaderFactory.nextTcpPeer(BlockReaderFactory.java:746)
	at org.apache.hadoop.hdfs.BlockReaderFactory.getRemoteBlockReaderFromTcp(BlockReaderFactory.java:661)
	at org.apache.hadoop.hdfs.BlockReaderFactory.build(BlockReaderFactory.java:325)
	at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:566)
	at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:789)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:843)
	at org.apache.hadoop.fs.FSDataInputStream.read(FSDataInputStream.java:144)
2015-03-25 02:22:40,829 WARN  [main] hdfs.DFSClient (DFSInputStream.java:blockSeekTo(601)) - Failed to connect to /127.0.0.1:1004 for block, add to deadNodes and continue. java.net.ConnectException: Connection refused

**Comment by mdrio** [comment]
Hi, in principle we are not doing anything bad with Kerberos, so I would except it to work. What happens if you try to do the same thing using hadoop command line interface, e.g., hdfs dfs -mkdir xxx?

**Comment by nilesh-unifi** [comment]
Hadoop CLI interface works fine ... Issue occurs when trying using pydoop. Here's my sample code:

import pydoop.hdfs as hdfs
import subprocess

p = subprocess.Popen('kinit xxxxx -k -t /tmp/xxxx.keytab', shell=True)
p.wait()

dir = hdfs.ls('/user')  # This works fine
print "The directories are: %s" % dir

with hdfs.open('/user/xxxx/files/order.csv', mode='r') as fh:
        buf = fh.read(16*1024)  # This does not work
        print "file contents are: %s" % buf

**Comment by elzaggo** [comment]
Hi there.
We did some testing using CDH  [vagrant.cdh.single (CDH5.3)] with kerberos enabled. As far as we can see, it works as expected. Could you provide some more details on your configuration?

The python code used is the following.
```python
import pydoop.hdfs as hdfs
import subprocess
p = subprocess.Popen('kinit vagrant@VMCLUSTER -k -t ./vagrant.keytab',
                     shell=True)
p.wait()

dir = hdfs.ls('/user')
print "The directories are: %s" % dir

with hdfs.open('/user/vagrant/foobar.csv', mode='w') as fh:
    fh.write('foobar\n')

with hdfs.open('/user/vagrant/foobar.csv', mode='r') as fh:
    data = fh.read()
    print 'data:', data
```

It appears to work fine:
```bash
vagrant@vm-cluster-node1:~$ kdestroy
kdestroy: No credentials cache found while destroying cache
vagrant@vm-cluster-node1:~$ python /vagrant/try_kerberos.py 
The directories are: [u'hdfs://vm-cluster-node1.vmcluster:8020/user/history', u'hdfs://vm-cluster-node1.vmcluster:8020/user/vagrant']
data: foobar
vagrant@vm-cluster-node1:~$ kdestroy
vagrant@vm-cluster-node1:~$ ipython
Python 2.7.3 (default, Dec 18 2014, 19:10:20) 
Type "copyright", "credits" or "license" for more information.

IPython 0.12.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pydoop.hdfs as hdfs

In [2]: fs = hdfs.hdfs()

In [3]: fs.list_directory('/user')
2015-04-01 14:33:13,093 WARN  [main] security.UserGroupInformation (UserGroupInformation.java:doAs(1645)) - PriviledgedActionException as:vagrant (auth:KERBEROS) cause:javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
2015-04-01 14:33:13,097 WARN  [main] ipc.Client (Client.java:run(674)) - Exception encountered while connecting to the server : javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
2015-04-01 14:33:13,097 WARN  [main] security.UserGroupInformation 
       ..... many lines removed .......
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:717)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:713)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1642)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:712)
	... 20 more
Caused by: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
	at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:147)
	at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:121)
	at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187)
	at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:223)
	at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212)
	at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)
	at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:193)
	... 29 more
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
/home/vagrant/<ipython-input-3-164275cad573> in <module>()
----> 1 fs.list_directory('/user')

/home/vagrant/.local/lib/python2.7/site-packages/pydoop-1.0.0-py2.7.egg/pydoop/hdfs/fs.pyc in list_directory(self, path)
    409         """
    410         _complain_ifclosed(self.closed)
--> 411         return self.fs.list_directory(path)
    412 
    413     def move(self, from_path, to_hdfs, to_path):

IOError: [Errno 255] Unknown error 255

In [4]: 

```

**Comment by nilesh-unifi** [comment]
Hi,

Yes, this works fine for me as well. Thanks a lot for taking time and looking into this. It was some configuration issue on the hadoop side (datanode) which was not letting it work. 

Once again, thanks a lot...

Regards,
Nilesh

**Comment by elzaggo** [comment]
no problems :-)

**Comment by nilesh-unifi** [comment]
Hi There,

I am however getting this error very frequently. Not sure if its pydoop or is it problem with hadoop again.

2015-04-02 04:57:36,543 WARN  [Thread-6] security.UserGroupInformation (UserGroupInformation.java:doAs(1557)) - PriviledgedActionException as:unifi (auth:SIMPLE) cause:org.apache.hadoop.security.AccessControlException: Client cannot authenticate via:[TOKEN, KERBEROS]
2015-04-02 04:57:36,544 WARN  [Thread-6] ipc.Client (Client.java:run(672)) - Exception encountered while connecting to the server : org.apache.hadoop.security.AccessControlException: Client cannot authenticate via:[TOKEN, KERBEROS]
2015-04-02 04:57:36,544 WARN  [Thread-6] security.UserGroupInformation (UserGroupInformation.java:doAs(1557)) - PriviledgedActionException as:unifi (auth:SIMPLE) cause:java.io.IOException: org.apache.hadoop.security.AccessControlException: Client cannot authenticate via:[TOKEN, KERBEROS]
hdfsGetPathInfo(/user/unifi/unifi_output/248_Unifi_test_to_check_csv_file_patterns_from_local_hdfs./schedule_170_2015-04-02_00_51_05_362302): getFileInfo error:
java.io.IOException: Failed on local exception: java.io.IOException: org.apache.hadoop.security.AccessControlException: Client cannot authenticate via:[TOKEN, KERBEROS]; Host Details : local host is: "ebe93b81e98e/172.17.0.2"; destination host is: "quickstart.cloudera":8020; 
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:764)
	at org.apache.hadoop.ipc.Client.call(Client.java:1413)
	at org.apache.hadoop.ipc.Client.call(Client.java:1362)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:206)
	at com.sun.proxy.$Proxy9.getFileInfo(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:186)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy9.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:701)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1758)
	at org.apache.hadoop.hdfs.DistributedFileSystem$17.doCall(DistributedFileSystem.java:1124)
	at org.apache.hadoop.hdfs.DistributedFileSystem$17.doCall(DistributedFileSystem.java:1120)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1120)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1398)
Caused by: java.io.IOException: org.apache.hadoop.security.AccessControlException: Client cannot authenticate via:[TOKEN, KERBEROS]
	at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:677)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1554)
	at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:640)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:724)
	at org.apache.hadoop.ipc.Client$Connection.access$2800(Client.java:367)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1461)
	at org.apache.hadoop.ipc.Client.call(Client.java:1380)
	... 17 more
Caused by: org.apache.hadoop.security.AccessControlException: Client cannot authenticate via:[TOKEN, KERBEROS]
	at org.apache.hadoop.security.SaslRpcClient.selectSaslClient(SaslRpcClient.java:170)
	at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:393)
	at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:550)
	at org.apache.hadoop.ipc.Client$Connection.access$1800(Client.java:367)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:716)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:712)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1554)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:711)
	... 20 more

Regards,
Nilesh

**Comment by elzaggo** [comment]
Hi.

It seems to be hadoop/kerberos related. Maybe a problem with time
synchronization between nodes?

--gianluigi
