### ISSUE TITLE
Enumerating large directories fails

### ISSUE THREAD

**Issue by jkm137** [crs4/pydoop#130]
When trying to enumerate a directory with ~45k files, I see this error:

hdfs.ls("/foo")

>hdfsListDirectory(hdfs://mymachine:8020/foo): FileSystem#listStatus error:
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOfRange(Arrays.java:2694)
        at java.lang.String.<init>(String.java:203)
        at java.lang.String.substring(String.java:1913)
        at java.net.URI$Parser.substring(URI.java:2850)
        at java.net.URI$Parser.parseHostname(URI.java:3379)
        at java.net.URI$Parser.parseServer(URI.java:3217)
        at java.net.URI$Parser.parseAuthority(URI.java:3136)
        at java.net.URI$Parser.parseHierarchical(URI.java:3078)
        at java.net.URI$Parser.parse(URI.java:3034)
        at java.net.URI.<init>(URI.java:753)
        at org.apache.hadoop.fs.Path.initialize(Path.java:203)
        at org.apache.hadoop.fs.Path.<init>(Path.java:116)
        at org.apache.hadoop.fs.Path.<init>(Path.java:94)
        at org.apache.hadoop.hdfs.protocol.HdfsFileStatus.getFullPath(HdfsFileStatus.java:227)
        at org.apache.hadoop.hdfs.protocol.HdfsFileStatus.makeQualified(HdfsFileStatus.java:255)
        at org.apache.hadoop.hdfs.DistributedFileSystem.listStatusInternal(DistributedFileSystem.java:693)
        at org.apache.hadoop.hdfs.DistributedFileSystem.access$600(DistributedFileSystem.java:104)
        at org.apache.hadoop.hdfs.DistributedFileSystem$14.doCall(DistributedFileSystem.java:716)
        at org.apache.hadoop.hdfs.DistributedFileSystem$14.doCall(DistributedFileSystem.java:712)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.listStatus(DistributedFileSystem.java:712)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pydoop/hdfs/__init__.py", line 312, in ls
    dir_list = lsl(hdfs_path, user, recursive)
  File "/usr/local/lib/python2.7/dist-packages/pydoop/hdfs/__init__.py", line 293, in lsl
    dir_list = fs.list_directory(path_)
  File "/usr/local/lib/python2.7/dist-packages/pydoop/hdfs/fs.py", line 411, in list_directory
    return self.fs.list_directory(path)
IOError: [Errno 12] Cannot allocate memory

Thanks in advance for your help!

**Comment by elzaggo** [comment]
Hi. 

Short answer: 
Increase the amount of memory granted to the jvm used by pydoop.hdfs. The default is 48m. I am not sure on the amount of  memory needed in your case, try doubling the default.
```bash
bash$ export LIBHDFS_OPTS ="-Xmx96m"
bash$ python -c "from pydoop import hdfs; hdfs.ls('/')"
```

Long answer:
```
Help on package pydoop.hdfs in pydoop:

NAME
    pydoop.hdfs

DESCRIPTION
    This module allows you to connect to an HDFS installation, read and
    write files and get information on files, directories and global
    filesystem properties.
    
    
    Configuration
    -------------
    
    The hdfs module is built on top of ``libhdfs``, in turn a JNI wrapper
    around the Java fs code: therefore, for the module to work properly,
    the ``CLASSPATH`` environment variable must include all paths to the
    relevant Hadoop jars. Pydoop will do this for you, but it needs to
    know where your Hadoop installation is located and what is your hadoop
    configuration directory: if Pydoop is not able to automatically find
    these directories, you have to make sure that the ``HADOOP_HOME`` and
    ``HADOOP_CONF_DIR`` environment variables are set to the appropriate
    values.
    
    Another important environment variable for this module is
    ``LIBHDFS_OPTS``\ . This is used to set options for the JVM on top of
    which the module runs, most notably the amount of memory it uses. If
    ``LIBHDFS_OPTS`` is not set, the C libhdfs will let it fall back to
    the default for your system, typically 1 GB. According to our
    experience, this is *much* more than most applications need and adds a
    lot of unnecessary memory overhead. For this reason, the hdfs module
    sets ``LIBHDFS_OPTS`` to ``-Xmx48m``\ , a value that we found to be
    appropriate for most applications.  If your needs are different, you
    can set the environment variable externally and it will override the
    above setting.
```

Cheers,

--gianluigi

**Comment by jkm137** [comment]
That solved my problem (96m was enough).  Thanks for the quick response!
