### ISSUE TITLE
uber mode crash

### ISSUE THREAD

**Issue by mdrio** [crs4/pydoop#152]
Uber Mode seems to be broken when using pydoop Submitter:

2015-07-03 17:08:46,165 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskAttemptImpl: Diagnostics report from attempt_1435935758118_0005_m_000001_0: java.lang.NullPointerException
	at org.apache.hadoop.mapred.pipes.Application.<init>(Application.java:104)
	at org.apache.hadoop.mapred.pipes.PipesMapRunner.run(PipesMapRunner.java:69)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:450)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
	at org.apache.hadoop.mapred.LocalContainerLauncher$EventHandler.runSubtask(LocalContainerLauncher.java:370)
	at org.apache.hadoop.mapred.LocalContainerLauncher$EventHandler.runTask(LocalContainerLauncher.java:295)
	at org.apache.hadoop.mapred.LocalContainerLauncher$EventHandler.access$200(LocalContainerLauncher.java:181)
	at org.apache.hadoop.mapred.LocalContainerLauncher$EventHandler$1.run(LocalContainerLauncher.java:224)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

For reproducing it, run in examples/wordcount dir:

 python run_wc.py bin/wordcount-minimal.py ../input -D mapreduce.job.ubertask.enable=true  -D mapred.reduce.tasks=1

**Comment by ilveroluca** [comment]
Suspect it's rooted at the same cause as #181

**Comment by elzaggo** [comment]
Most likely is due to a collision with the multi-threading needed by pipes. See [here](http://stackoverflow.com/questions/30284237/what-is-the-purpose-of-uber-mode-in-hadoop).
Wont-fix.
