### ISSUE TITLE
pip install pydoop fails

### ISSUE THREAD

**Issue by earthquakesan** [crs4/pydoop#170]
$HADOOP_HOME is set, I also tried to set it explicitly (see the stacktrace below).
Installing from the repo is ok (python setup.py build)

```
iermilov@node104:~/pydoop$ env HADOOP_HOME=/home/iermilov/hadoop-2.6.2 sudo pip install pydoop
Downloading/unpacking pydoop
  Downloading pydoop-1.1.0.tar.gz (957kB): 957kB downloaded
  Running setup.py (path:/tmp/pip_build_root/pydoop/setup.py) egg_info for package pydoop
    using setuptools version 3.3
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/pydoop/setup.py", line 67, in <module>
        import pydoop.hdfs.core.impl as hdfsimpl
      File "pydoop/hdfs/__init__.py", line 99, in <module>
        init()
      File "pydoop/hdfs/__init__.py", line 93, in init
        pydoop.hadoop_classpath(), _ORIG_CLASSPATH, pydoop.hadoop_conf()
      File "pydoop/__init__.py", line 111, in hadoop_classpath
        return _PATH_FINDER.hadoop_classpath(hadoop_home)
      File "pydoop/hadoop_utils.py", line 573, in hadoop_classpath
        hadoop_home = self.hadoop_home()
      File "pydoop/hadoop_utils.py", line 428, in hadoop_home
        PathFinder.__error("hadoop home", "HADOOP_HOME")
      File "pydoop/hadoop_utils.py", line 414, in __error
        raise ValueError("%s not found, try setting %s" % (what, env_var))
    ValueError: hadoop home not found, try setting HADOOP_HOME
    Complete output from command python setup.py egg_info:
    using setuptools version 3.3

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/pydoop/setup.py", line 67, in <module>

    import pydoop.hdfs.core.impl as hdfsimpl

  File "pydoop/hdfs/__init__.py", line 99, in <module>

    init()

  File "pydoop/hdfs/__init__.py", line 93, in init

    pydoop.hadoop_classpath(), _ORIG_CLASSPATH, pydoop.hadoop_conf()

  File "pydoop/__init__.py", line 111, in hadoop_classpath

    return _PATH_FINDER.hadoop_classpath(hadoop_home)

  File "pydoop/hadoop_utils.py", line 573, in hadoop_classpath

    hadoop_home = self.hadoop_home()

  File "pydoop/hadoop_utils.py", line 428, in hadoop_home

    PathFinder.__error("hadoop home", "HADOOP_HOME")

  File "pydoop/hadoop_utils.py", line 414, in __error

    raise ValueError("%s not found, try setting %s" % (what, env_var))

ValueError: hadoop home not found, try setting HADOOP_HOME

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pydoop
Storing debug log for failure in /home/iermilov/.pip/pip.log
```

**Comment by mdrio** [comment]
Hi, please try sudo -E pip install pydoop to preserve the environment.

Il giorno lun 23 nov 2015 13:33 Ivan Ermilov <notifications@github.com> ha
scritto:
