### ISSUE TITLE
MapReduce error with custom reader

### ISSUE THREAD

**Issue by vkuznet** [crs4/pydoop#175]
Based on trials I figure it out proper structure to submit my job to Hadoop. But then I experience Java exception problem which I don't understand. I would appreciate any hints you can give to me. Here is the error I got:

```
Error: java.lang.ClassCastException: org.apache.hadoop.io.Text cannot be cast to org.apache.avro.generic.IndexedRecord
        at it.crs4.pydoop.mapreduce.pipes.PydoopAvroBridgeValueReader.getInRecords(PydoopAvroBridgeValueReader.java:32)
        at it.crs4.pydoop.mapreduce.pipes.PydoopAvroBridgeReaderBase.initialize(PydoopAvroBridgeReaderBase.java:69)
        at it.crs4.pydoop.mapreduce.pipes.PydoopAvroBridgeValueReader.initialize(PydoopAvroBridgeValueReader.java:38)
        at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.initialize(MapTask.java:548)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:786)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
```

My python code is the following:
```
# system modules
import os
import sys

# pydoop modules
import pydoop.mapreduce.api as api
import pydoop.mapreduce.pipes as pp
from pydoop.avrolib import AvroContext

# WMA modules which implement reading the file from HDFS
from WMA.Storage.HdfsIO import HdfsStorage

class Reader(api.RecordReader):
    def __init__(self, context):
        super(Reader, self).__init__(context)
        print "### WMA MP Reader", context, type(context)
        uri = os.getenv('WMA_SCHEMA')
        mgr = HdfsStorage(uri)
        fid = context.input_split.filename.split('.')[0] # use only name, not extension
        self.data = mgr._read(fid)
        self.idx = 0 # first element

    def next(self):
        if  self.idx >= len(self.data)
            raise StopIteration
        rec = self.data[self.idx]
        self.idx += 1
        key = rec['jobid']
        return key, rec

    def get_progress(self):
        return float(self.idx)/len(self.data)

class Mapper(api.Mapper):
    def map(self, ctx):
        rec = ctx.value
        jid = rec['jobid']
        if jid is not None:
            ctx.emit(jid, rec['fwjr']['task'])

class Reducer(api.Reducer):
    def reduce(self, ctx):
        ctx.emit('', {'jobid': ctx.key, 'task': ctx.values})

def __main__():
    factory = pp.Factory(mapper_class=Mapper, reducer_class=Reducer, record_reader_class=Reader)
    pp.run_task(factory, private_encoding=True, context_class=AvroContext)
```

I'm not sure yet if I wrote Reader class correctly, but the point is that I don't see it is called in a job, I only saw aforementioned exception.

Here is my submission script

```
#!/bin/bash
source setup.sh
hdfs=hdfs://myhost:9000/user/myname/test/
schema=$(cat mr_output.avsc)
export WMA_SCHEMA=$hdfs/fwjr_proc.avsc
export PYTHONPATH=$PYTHONPATH:$PWD/WMA
input=$hdfs/data
output=$hdfs/mr_out
hadoop fs -rmdir $output
ifile=mr.py
module=mr
pydoop submit \
    -D pydoop.mapreduce.avro.value.output.schema="$schema" \
    --avro-input v --avro-output v \
    --do-not-use-java-record-reader \
    --no-override-env \
    --log-level DEBUG \
    --upload-file-to-cache $ifile \
    --mrv2 $module $input $output
```

Once I have better understanding of machinery and reason for error I can adjust code/submission script. So far I need some guidance to figure out what is the problem. From the printed error I'm not even sure if my mapper (with my reader) is called.
Thanks,
Valentin.

**Comment by vkuznet** [comment]
I think the reason for my error is caused by these parameters ```--avro-input v --avro-output v``` which instructs pydoop that my reader will be io.Text. And, if I use custom Reader then I don't need to specify these options.

**Comment by vkuznet** [comment]
I confirmed that for custom reader/writer I don't need to specify --avro-input/--avro-output. The issue is resolved.
