### ISSUE TITLE
How to tell pydoop to upload itself

### ISSUE THREAD

**Issue by vkuznet** [crs4/pydoop#176]
Hi, I'm struggling to run my MR job on our hadoop cluster. Turns out the problem is that pydoop is not installed over there and my local paths (where I install the pydoop) are not accessible from worker nodes.  I got the following error in one of my tasks:
```
Traceback (most recent call last):
  File "/data19/yarn/local/usercache/valya/appcache/application_1446446075159_41836/container_1446446075159_41836_01_000002/fb6acc41-8dae-4d4a-b4c9-fc413fd0a20f", line 19, in <module>
    import mr as module
  File "/data19/yarn/local/usercache/valya/appcache/application_1446446075159_41836/container_1446446075159_41836_01_000002/mr.py", line 17, in <module>
    import pydoop.mapreduce.api as api
ImportError: No module named pydoop.mapreduce.api
```

it means that I need to upload pydoop to worker node in order to run my code. Therefore my question is how to tell pydoop to upload tarball, untar it and setup environment.
There are few options I found in pydoop submit command, like --python-zip, --upload-archive-to-cache, but I don't know how I can untar archive over there and set proper environment.
Thanks,
Valentin.

**Comment by vkuznet** [comment]
After searching around I finally found an answer in pydoop documentation itself
http://crs4.github.io/pydoop/self_contained.html
and later this example
https://github.com/crs4/pydoop/blob/master/examples/self_contained/Makefile
which completely answers my original question.
