### ISSUE TITLE
win7 64 bit "pip install pydoop" Error

### ISSUE THREAD

**Issue by xyniceboy** [crs4/pydoop#184]
C:\Windows\System32>pip install pydoop
Collecting pydoop
  Using cached pydoop-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    using setuptools version 19.4
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\admini~1\appdata\local\temp\pip-build-tr7gie\pydoop\setup.p
        _ for _ in get_config_var('OPT').strip().split() if _ not in _UNWANTED_O
    AttributeError: 'NoneType' object has no attribute 'strip'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\admini~1oop

C:\Windows\System32>

**Comment by xyniceboy** [comment]
C:\Windows\System32>pip install pydoop
Collecting pydoop
  Using cached pydoop-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    using setuptools version 19.4
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\admini~1\appdata\local\temp\pip-build-tr7gie\pydoop\setup.py", line 56, in <module>
        _ for _ in get_config_var('OPT').strip().split() if _ not in _UNWANTED_OPTS
    AttributeError: 'NoneType' object has no attribute 'strip'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\admini~1\appdata\local\temp\pip-build-tr7gie\pydoop

C:\Windows\System32>
