### ISSUE TITLE
[ImportError] import pydoop.hdfs

### ISSUE THREAD

**Issue by xyniceboy** [crs4/pydoop#187]
>>> import pydoop
>>> import pydoop.hdfs as hdfs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydoop/hdfs/__init__.py", line 82, in <module>
    from . import common, path
ImportError: cannot import name common
>>>

**Comment by xyniceboy** [comment]
[root@zdh3en hdfs]# pwd
/usr/local/lib/python2.7/site-packages/pydoop/hdfs
[root@zdh3en hdfs]# ls
common.py  common.pyc  core  file.py  file.pyc  fs.py  fs.pyc  __init__.py  __init__.pyc  path.py  path.pyc
[root@zdh3en hdfs]# vim __init__.py
 79 import os
 80 
 81 import pydoop
 82 from . import common, path
 83 
 84 try:
 85     _ORIG_CLASSPATH
 86 except NameError:
 87     _ORIG_CLASSPATH = os.getenv("CLASSPATH", "")
"/usr/local/lib/python2.7/site-packages/pydoop/hdfs/__init__.py" 387 lines --15%--

**Comment by xyniceboy** [comment]
After configure the parameter, "import pydoop.hdfs" is ok.

HADOOP_VERSION=2.5.0-zdh2.0.2-hdfs-SNAPSHOT
HADOOP_HOME=/home/hdfs/hdfs
HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop

export HADOOP_VERSION HADOOP_HOME  HADOOP_CONF_DIR
