### ISSUE TITLE
missing jni.h

### ISSUE THREAD

**Issue by siliconplains44** [crs4/pydoop#199]
I have java installed but I am getting this message on pip install pydoop in ubuntu 14.04 lts.

```
pip install pydoop
Downloading/unpacking pydoop
  Downloading pydoop-1.1.0.tar.gz (957kB): 957kB downloaded
  Running setup.py (path:/tmp/pip_build_allan/pydoop/setup.py) egg_info for package pydoop
    using setuptools version 3.3

    warning: no previously-included files matching '*' found under directory 'examples/wordcount/c++'
Requirement already satisfied (use --upgrade to upgrade): setuptools>=3.3 in /usr/lib/python2.7/dist-packages (from pydoop)
Installing collected packages: pydoop
  Running setup.py install for pydoop
    using setuptools version 3.3
    hdfs core implementation: native
    building 'pydoop.sercore' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -I/usr/include/python2.7 -c src/serialize/protocol_codec.cc -o build/temp.linux-x86_64-2.7/src/serialize/protocol_codec.o -Wno-write-strings -O3
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -I/usr/include/python2.7 -c src/serialize/SerialUtils.cc -o build/temp.linux-x86_64-2.7/src/serialize/SerialUtils.o -Wno-write-strings -O3
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -I/usr/include/python2.7 -c src/serialize/StringUtils.cc -o build/temp.linux-x86_64-2.7/src/serialize/StringUtils.o -Wno-write-strings -O3
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/serialize/protocol_codec.o build/temp.linux-x86_64-2.7/src/serialize/SerialUtils.o build/temp.linux-x86_64-2.7/src/serialize/StringUtils.o -o build/lib.linux-x86_64-2.7/pydoop/sercore.so
    building 'pydoop.native_core_hdfs' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -DHADOOP_LIBHDFS_V2=1 -I/usr/include -Inative/jni_include -I/usr/lib -I/usr/include/linux -Isrc/libhdfsV2 -Isrc/libhdfsV2/os/posix -I/usr/include/python2.7 -c src/libhdfsV2/native_mini_dfs.c -o build/temp.linux-x86_64-2.7/src/libhdfsV2/native_mini_dfs.o -Wno-write-strings
    In file included from src/libhdfsV2/os/posix/platform.h:22:0,
                     from src/libhdfsV2/exception.h:37,
                     from src/libhdfsV2/native_mini_dfs.c:19:
    /usr/include/pthread.h:317:11: error: unknown type name ‘size_t’
               size_t *__guardsize)
               ^
    /usr/include/pthread.h:322:11: error: unknown type name ‘size_t’
               size_t __guardsize)
               ^
    /usr/include/pthread.h:380:19: error: unknown type name ‘size_t’
               __attr, size_t *__restrict __stacksize)
                       ^
    /usr/include/pthread.h:387:11: error: unknown type name ‘size_t’
               size_t __stacksize)
               ^
    /usr/include/pthread.h:394:7: error: unknown type name ‘size_t’
           size_t *__restrict __stacksize)
           ^
    /usr/include/pthread.h:401:7: error: unknown type name ‘size_t’
           size_t __stacksize) __THROW __nonnull ((1));
           ^
    In file included from src/libhdfsV2/native_mini_dfs.c:19:0:
    src/libhdfsV2/exception.h:39:17: fatal error: jni.h: No such file or directory
     #include <jni.h>
                     ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_allan/pydoop/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-5b5CXJ-record/install-record.txt --single-version-externally-managed --compile:
    using setuptools version 3.3

running install

running build

hdfs core implementation: native

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/pydoop

copying pydoop/hadoop_utils.py -> build/lib.linux-x86_64-2.7/pydoop

copying pydoop/avrolib.py -> build/lib.linux-x86_64-2.7/pydoop

copying pydoop/version.py -> build/lib.linux-x86_64-2.7/pydoop

copying pydoop/jc.py -> build/lib.linux-x86_64-2.7/pydoop

copying pydoop/test_support.py -> build/lib.linux-x86_64-2.7/pydoop

copying pydoop/config.py -> build/lib.linux-x86_64-2.7/pydoop

copying pydoop/__init__.py -> build/lib.linux-x86_64-2.7/pydoop

copying pydoop/test_utils.py -> build/lib.linux-x86_64-2.7/pydoop

copying pydoop/pipes.py -> build/lib.linux-x86_64-2.7/pydoop

copying pydoop/hadut.py -> build/lib.linux-x86_64-2.7/pydoop

creating build/lib.linux-x86_64-2.7/pydoop/app

copying pydoop/app/submit.py -> build/lib.linux-x86_64-2.7/pydoop/app

copying pydoop/app/script.py -> build/lib.linux-x86_64-2.7/pydoop/app

copying pydoop/app/script_template.py -> build/lib.linux-x86_64-2.7/pydoop/app

copying pydoop/app/argparse_types.py -> build/lib.linux-x86_64-2.7/pydoop/app

copying pydoop/app/__init__.py -> build/lib.linux-x86_64-2.7/pydoop/app

copying pydoop/app/main.py -> build/lib.linux-x86_64-2.7/pydoop/app

creating build/lib.linux-x86_64-2.7/pydoop/mapreduce

copying pydoop/mapreduce/api.py -> build/lib.linux-x86_64-2.7/pydoop/mapreduce

copying pydoop/mapreduce/binary_streams.py -> build/lib.linux-x86_64-2.7/pydoop/mapreduce

copying pydoop/mapreduce/string_utils.py -> build/lib.linux-x86_64-2.7/pydoop/mapreduce

copying pydoop/mapreduce/streams.py -> build/lib.linux-x86_64-2.7/pydoop/mapreduce

copying pydoop/mapreduce/simulator.py -> build/lib.linux-x86_64-2.7/pydoop/mapreduce

copying pydoop/mapreduce/__init__.py -> build/lib.linux-x86_64-2.7/pydoop/mapreduce

copying pydoop/mapreduce/connections.py -> build/lib.linux-x86_64-2.7/pydoop/mapreduce

copying pydoop/mapreduce/pipes.py -> build/lib.linux-x86_64-2.7/pydoop/mapreduce

copying pydoop/mapreduce/jwritable_utils.py -> build/lib.linux-x86_64-2.7/pydoop/mapreduce

copying pydoop/mapreduce/text_streams.py -> build/lib.linux-x86_64-2.7/pydoop/mapreduce

creating build/lib.linux-x86_64-2.7/pydoop/hdfs

copying pydoop/hdfs/file.py -> build/lib.linux-x86_64-2.7/pydoop/hdfs

copying pydoop/hdfs/fs.py -> build/lib.linux-x86_64-2.7/pydoop/hdfs

copying pydoop/hdfs/path.py -> build/lib.linux-x86_64-2.7/pydoop/hdfs

copying pydoop/hdfs/common.py -> build/lib.linux-x86_64-2.7/pydoop/hdfs

copying pydoop/hdfs/__init__.py -> build/lib.linux-x86_64-2.7/pydoop/hdfs

creating build/lib.linux-x86_64-2.7/pydoop/utils

copying pydoop/utils/misc.py -> build/lib.linux-x86_64-2.7/pydoop/utils

copying pydoop/utils/serialize.py -> build/lib.linux-x86_64-2.7/pydoop/utils

copying pydoop/utils/jvm.py -> build/lib.linux-x86_64-2.7/pydoop/utils

copying pydoop/utils/conversion_tables.py -> build/lib.linux-x86_64-2.7/pydoop/utils

copying pydoop/utils/__init__.py -> build/lib.linux-x86_64-2.7/pydoop/utils

creating build/lib.linux-x86_64-2.7/pydoop/hdfs/core

copying pydoop/hdfs/core/impl.py -> build/lib.linux-x86_64-2.7/pydoop/hdfs/core

copying pydoop/hdfs/core/api.py -> build/lib.linux-x86_64-2.7/pydoop/hdfs/core

copying pydoop/hdfs/core/__init__.py -> build/lib.linux-x86_64-2.7/pydoop/hdfs/core

creating build/lib.linux-x86_64-2.7/pydoop/utils/bridge

copying pydoop/utils/bridge/factory.py -> build/lib.linux-x86_64-2.7/pydoop/utils/bridge

copying pydoop/utils/bridge/jpype_loader.py -> build/lib.linux-x86_64-2.7/pydoop/utils/bridge

copying pydoop/utils/bridge/pyjnius_loader.py -> build/lib.linux-x86_64-2.7/pydoop/utils/bridge

copying pydoop/utils/bridge/__init__.py -> build/lib.linux-x86_64-2.7/pydoop/utils/bridge

creating build/lib.linux-x86_64-2.7/pydoop/hdfs/core/bridged

copying pydoop/hdfs/core/bridged/hadoop.py -> build/lib.linux-x86_64-2.7/pydoop/hdfs/core/bridged

copying pydoop/hdfs/core/bridged/common.py -> build/lib.linux-x86_64-2.7/pydoop/hdfs/core/bridged

copying pydoop/hdfs/core/bridged/__init__.py -> build/lib.linux-x86_64-2.7/pydoop/hdfs/core/bridged

copying pydoop/pydoop.properties -> build/lib.linux-x86_64-2.7/pydoop

running build_ext

building 'pydoop.sercore' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/src

creating build/temp.linux-x86_64-2.7/src/serialize

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -I/usr/include/python2.7 -c src/serialize/protocol_codec.cc -o build/temp.linux-x86_64-2.7/src/serialize/protocol_codec.o -Wno-write-strings -O3

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -I/usr/include/python2.7 -c src/serialize/SerialUtils.cc -o build/temp.linux-x86_64-2.7/src/serialize/SerialUtils.o -Wno-write-strings -O3

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -I/usr/include/python2.7 -c src/serialize/StringUtils.cc -o build/temp.linux-x86_64-2.7/src/serialize/StringUtils.o -Wno-write-strings -O3

c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/serialize/protocol_codec.o build/temp.linux-x86_64-2.7/src/serialize/SerialUtils.o build/temp.linux-x86_64-2.7/src/serialize/StringUtils.o -o build/lib.linux-x86_64-2.7/pydoop/sercore.so

building 'pydoop.native_core_hdfs' extension

creating build/temp.linux-x86_64-2.7/src/libhdfsV2

creating build/temp.linux-x86_64-2.7/src/libhdfsV2/common

creating build/temp.linux-x86_64-2.7/src/libhdfsV2/os

creating build/temp.linux-x86_64-2.7/src/libhdfsV2/os/posix

creating build/temp.linux-x86_64-2.7/src/native_core_hdfs

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -DHADOOP_LIBHDFS_V2=1 -I/usr/include -Inative/jni_include -I/usr/lib -I/usr/include/linux -Isrc/libhdfsV2 -Isrc/libhdfsV2/os/posix -I/usr/include/python2.7 -c src/libhdfsV2/native_mini_dfs.c -o build/temp.linux-x86_64-2.7/src/libhdfsV2/native_mini_dfs.o -Wno-write-strings

In file included from src/libhdfsV2/os/posix/platform.h:22:0,

                 from src/libhdfsV2/exception.h:37,

                 from src/libhdfsV2/native_mini_dfs.c:19:

/usr/include/pthread.h:317:11: error: unknown type name ‘size_t’

           size_t *__guardsize)

           ^

/usr/include/pthread.h:322:11: error: unknown type name ‘size_t’

           size_t __guardsize)

           ^

/usr/include/pthread.h:380:19: error: unknown type name ‘size_t’

           __attr, size_t *__restrict __stacksize)

                   ^

/usr/include/pthread.h:387:11: error: unknown type name ‘size_t’

           size_t __stacksize)

           ^

/usr/include/pthread.h:394:7: error: unknown type name ‘size_t’

       size_t *__restrict __stacksize)

       ^

/usr/include/pthread.h:401:7: error: unknown type name ‘size_t’

       size_t __stacksize) __THROW __nonnull ((1));

       ^

In file included from src/libhdfsV2/native_mini_dfs.c:19:0:

src/libhdfsV2/exception.h:39:17: fatal error: jni.h: No such file or directory

 #include <jni.h>

                 ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_allan/pydoop/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-5b5CXJ-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_allan/pydoop
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 60: ordinal not in range(128)
```

**Comment by ilveroluca** [comment]
You need to install the JDK.

**Comment by siliconplains44** [comment]
I have... still fails... I have the oracle 8 jdk

On Wednesday, February 24, 2016, Luca Pireddu <notifications@github.com>
wrote:

> You need to install the JDK.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crs4/pydoop/issues/199#issuecomment-188152582>.
>


-- 
W Allan Edwards
214-289-2959

**Comment by ilveroluca** [comment]
Did you set the JAVA_HOME environment variable to point to the JDK?  Oh, and don't forget to export it too.  On my system

```
[me@host ~] ls $JAVA_HOME/include/ 
classfile_constants.h  jawt.h  jdwpTransport.h  jni.h  jvmti.h  jvmticmlr.h  linux
```

**Comment by simleo** [comment]
Also, your build output contains some weird `unknown type name ‘size_t’` errors. Are you sure your development environment is sane? Did you run `sudo apt-get install build-essential`?

**Comment by Omnipresent** [comment]
I'm having the same problem on centOS7. I have Java installed and it is exported:

```
[root@localhost lib]# cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core)
[root@localhost lib]# echo $JAVA_HOME
/usr/lib/jvm/jre-1.7.0-openjdk
[root@localhost lib]# ls -al $JAVA_HOME
lrwxrwxrwx. 1 root root 35 Jul 11 11:24 /usr/lib/jvm/jre-1.7.0-openjdk -> /etc/alternatives/jre_1.7.0_openjdk
[root@localhost lib]# ls /usr/lib/jvm/jre-1.7.0-openjdk
bin  lib
```

`pip install pydoop`

>     In file included from src/libhdfsV2/exception.c:19:0:
>     src/libhdfsV2/exception.h:39:17: fatal error: jni.h: No such file or directory
>      #include <jni.h>
>                      ^
>     compilation terminated.
>     error: command 'gcc' failed with exit status 1
>

**Comment by ilveroluca** [comment]
This is old, but I'm going to add another comment before closing.

Your JAVA_HOME is missing the `include` directory (where you'd find the file jni.h).  It looks like you need to install some development files for your version of Java.

**Comment by simleo** [comment]
> It looks like you need to install some development files for your version of Java

Yes, the JDK package to install is the one with the `-devel` tag, e.g.:

```
yum install java-1.8.0-openjdk-devel
```
