### ISSUE TITLE
hdfs.ls() - IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by BlancKami** [crs4/pydoop#213]
I'm trying to use hdfs.ls() on one of my csv file. The code: 

``` 
import pydoop.hdfs as hdfs

files = hdfs.ls('2007.csv') 
```
The error:

```
2016-04-18 10:11:16,012 WARN  [main] util.NativeCodeLoader (NativeCodeLoader.java:<clinit>(62)) - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    files = hdfs.ls('2007.csv') 
  File "/usr/local/lib/python2.7/site-packages/pydoop/hdfs/__init__.py", line 312, in ls
    dir_list = lsl(hdfs_path, user, recursive)
  File "/usr/local/lib/python2.7/site-packages/pydoop/hdfs/__init__.py", line 293, in lsl
    dir_list = fs.list_directory(path_)
  File "/usr/local/lib/python2.7/site-packages/pydoop/hdfs/fs.py", line 411, in list_directory
    return self.fs.list_directory(path)
IOError: [Errno 2] No such file or directory

```

I made sure that 2007.csv is in the same dir by testing it with open('2007.csv', 'rb').  Why did this error come up? and how to fix this?

**Comment by ilveroluca** [comment]
As with the `hdfs dfs -ls` command, the default current working directory is `/user/$USER/` on your default HDFS volume.  So, the relative path `2007.csv` points to `/user/$USER/2007.csv` on HDFS.  On the other hand, Python's `open` knows nothing about HDFS so it opened the file `2007.csv` in whatever your work directory was at the moment.

If you want to `ls` or open a local path with `pydoop.hdfs` you'll need to specify a full URI (something like `file:///home/$USER/mypath`).
