### ISSUE TITLE
Better error msg when import from dist dir is attempted

### ISSUE THREAD

**Issue by simleo** [crs4/pydoop#235]
Pydoop is not usable from the distribution directory, not even after compiling. Here is a typical error scenario:

```
>>> import pydoop.hdfs as hdfs
>>> fs = hdfs.hdfs()
Traceback (most recent call last):
  File "/build/pydoop/pydoop/hdfs/fs.py", line 154, in __init__
    self.__status = self.__lookup((host, port, user))
  File "/build/pydoop/pydoop/hdfs/fs.py", line 135, in __lookup
    return self._CACHE[hpu]
KeyError: ('default', 0, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/build/pydoop/pydoop/hdfs/fs.py", line 156, in __init__
    h, p, u, fs = _get_connection_info(host, port, user)
  File "/build/pydoop/pydoop/hdfs/fs.py", line 73, in _get_connection_info
    fs = core_hdfs_fs(host, port, user)
  File "/build/pydoop/pydoop/hdfs/core/__init__.py", line 55, in core_hdfs_fs
    'module not initialized, check that Pydoop is correctly installed'
RuntimeError: module not initialized, check that Pydoop is correctly installed
```

In this case, however, Pydoop was correctly installed. We should find a way to point the user to the real issue in our error message.

**Comment by simleo** [comment]
Done in #238.
