### ISSUE TITLE
Pydoop is not importable from an egg file

### ISSUE THREAD

**Issue by simleo** [crs4/pydoop#276]
```
>>> import sys
>>> sys.path.insert(0, "pydoop-1.2.0-py2.7.egg")
>>> import pydoop
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pydoop/__init__.py", line 194, in <module>
  File "build/bdist.linux-x86_64/egg/pydoop/__init__.py", line 179, in read_properties
IOError: [Errno 20] Not a directory: '/tmp/templib/pydoop-1.2.0-py2.7.egg/pydoop/pydoop.properties'
```

Tested with Pydoop 1.2.0, need to check if this also affects the current development branch. We could copy properties to a Python module as part of the installation process to avoid this.

**Comment by simleo** [comment]
Looks like it would break anyway when trying to import extension modules, see #273. Although http://peak.telecommunity.com/DevCenter/PythonEggs says it should be possible to make it work (together with pkg_resources), my attempts were unsuccessful. If we leave like this, at least we should add `zip_safe=False` to the `setup` function.

**Comment by srinivasachari** [comment]
Hi,
Using pkg_resources I managed to read yaml configuration from an egg file. Please check if this helps.
Folder structure is below:
```
testproject-1.0-py2.7.egg/
        setup.py
        requirements.txt
        rdf/
             src
             .....
             config.yaml
from pkg_resources import resource_exists, resource_stream
import yaml 
 
config_stream = resource_stream('rdf', 'config.yaml')
config = yaml.load(config_stream)
config.get(key, None)
```
