### ISSUE TITLE
input_format example fails: pydoop.hadoop_exec cannot find binary?

### ISSUE THREAD

**Issue by kikkomep** [crs4/pydoop#40]
root@faf2167bb952:~/Work/pydoop_versions/last/examples (develop)$ echo $PATH
/opt/hadoop/2.2.0/bin:/opt/hadoop/2.2.0/sbin:/opt/hadoop:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

However, it fails as if it could not find the hadoop binary

 *** RUNNING input_format EXAMPLE(S) ***

Traceback (most recent call last):
  File "./run", line 49, in <module>
    HADOOP = pydoop.hadoop_exec()
  File "/usr/local/lib/python2.7/dist-packages/pydoop/__init__.py", line 71, in hadoop_exec
    return _PATH_FINDER.hadoop_exec(hadoop_home)
  File "/usr/local/lib/python2.7/dist-packages/pydoop/hadoop_utils.py", line 414, in hadoop_exec
    PathFinder.__error("hadoop executable", "HADOOP_HOME or PATH")
  File "/usr/local/lib/python2.7/dist-packages/pydoop/hadoop_utils.py", line 369, in __error
    raise ValueError("%s not found, try setting %s" % (what, env_var))
ValueError: hadoop executable not found, try setting HADOOP_HOME or PATH

**Comment by elzaggo** [comment]
Solved a long time ago.
