### ISSUE TITLE
Jobs in stand-alone mode fail.

### ISSUE THREAD

**Issue by lucidfrontier45** [crs4/pydoop#7]
Hi all.

After reading the tutorial, I started testing the wordcount script in the examples with stand-alone mode (conf.empty of CDH4.3).

The command I issued is this. (I put some txt files to the input directory in advance.)
`mapred pipes -D hadoop.pipes.java.recordreader=true -D hadoop.pipes.java.recordwriter=true \
                     -program ./workspace/pydoop/examples/wordcount/bin/wordcount-minimal.py\
                     -input input -output output`

However it gave of the following error. What do I miss?
Thank you.

--------------------------------------------------------------------------------------------------------------------------
java.lang.Exception: java.lang.NullPointerException
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:406)
Caused by: java.lang.NullPointerException
	at org.apache.hadoop.mapred.pipes.Application.<init>(Application.java:103)
	at org.apache.hadoop.mapred.pipes.PipesMapRunner.run(PipesMapRunner.java:68)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:417)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:332)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:268)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:679)
13/10/17 23:59:28 INFO mapred.JobClient:  map 0% reduce 0%
13/10/17 23:59:28 INFO mapred.JobClient: Job complete: job_local1217616394_0001
13/10/17 23:59:28 INFO mapred.JobClient: Counters: 0
13/10/17 23:59:28 INFO mapred.JobClient: Job Failed: NA
Exception in thread "main" java.io.IOException: Job failed!
	at org.apache.hadoop.mapred.JobClient.runJob(JobClient.java:1372)
	at org.apache.hadoop.mapred.pipes.Submitter.runJob(Submitter.java:248)
	at org.apache.hadoop.mapred.pipes.Submitter.run(Submitter.java:479)
	at org.apache.hadoop.mapred.pipes.Submitter.main(Submitter.java:494)

**Comment by elzaggo** [comment]
Obsoleted by 1.0
