### ISSUE TITLE
OutOfMemoryError - tasks hang instead of fail

### ISSUE THREAD

**Issue by kmatzen** [crs4/pydoop#8]
If I set the JVM heap size to be too small, then I get this error in my logs.

org.apache.hadoop.mapred.pipes.BinaryProtocol: java.lang.OutOfMemoryError: Java heap spaaace

However, rather than the task failing, retrying, and eventually the job failing, the task just hangs.  I'm using the default 10 minute task timeout, but it still doesn't fail properly.

I'm using pydoop 0.10 with hadoop 1.2.1.  I don't recall having this issue with pydoop 0.9 and hadoop 1.1.2.

Here's the partial stack trace of the python process once it gets blocked.
```
#0  0x00000030154c750b in write () from /lib64/libc.so.6
#1  0x000000301546ae53 in _IO_new_file_write () from /lib64/libc.so.6
#2  0x000000301546c293 in _IO_new_file_xsputn () from /lib64/libc.so.6
#3  0x000000301546149b in fwrite () from /lib64/libc.so.6
#4  0x00002b9c244ef83f in HadoopUtils::FileOutStream::write (
    this=<value optimized out>, buf=0x590000, len=315064104)
    at src/hadoop-1.2.1.patched/utils/impl/SerialUtils.cc:129
#5  0x00002b9c244ccd74 in operator() (this=<value optimized out>,
    args=<value optimized out>, kw=<value optimized out>)
    at /tmp/kmatzen/prefix/include/boost/python/detail/invoke.hpp:94
#6  boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (HadoopPipes::TaskContext::*)(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), boost::python::default_call_policies, boost::mpl::vector4<void, HadoopPipes::MapContext&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&> > >::operator() (
    this=<value optimized out>, args=<value optimized out>,
    kw=<value optimized out>)
    at /tmp/kmatzen/prefix/include/boost/python/object/py_function.hpp:38
#7  0x00002b9c24760ef7 in boost::python::objects::function::call(_object*, _object*) const () from /tmp/kmatzen/prefix/lib/libboost_python.so.1.54.0
```

**Comment by elzaggo** [comment]
Closed.
