### ISSUE TITLE
Pydoop installtion fails on Linux hadoop cluster

### ISSUE THREAD

**Issue by shaliniravi** [crs4/pydoop#84]
I am getting this error When try to install pydoop

$ sudo pip install pydoop
Collecting pydoop
  Using cached pydoop-0.12.0.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-SftpT5/pydoop/setup.py", line 46, in <module>
        import pydoop
      File "pydoop/__init__.py", line 32, in <module>
        from importlib import import_module
    ImportError: No module named importlib
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-SftpT5/pydoop/setup.py", line 46, in <module>

        import pydoop

      File "pydoop/__init__.py", line 32, in <module>

        from importlib import import_module

    ImportError: No module named importlib

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-SftpT5/pydoop

Please tell me what is wrong ? how to install it properly.

**Comment by mdrio** [comment]
Hi, are you using python 2.6? In this case,  you need to install the following additional modules: [importlib](http://pypi.python.org/pypi/importlib) and [argparse](http://pypi.python.org/pypi/argparse).
In addition, I see you are using pydoop 0.12: you should try the last release 1.0, which is easier to install, supports many hadoop distributions and has more feautures.
